### ISSUE TITLE
I wrote a similar library

### ISSUE THREAD

**Issue by tacone** [revinate/sequence#6]
Hello I wrote a library very similar in intent to yours:
https://github.com/tacone/pipes (`pipes/pipes` on packagist)

I am contacting you because I thought you may have be interested in checking out a slightly different approach and/or (eventually) to unite efforts one day.

I hope to not have bothered you too much, feel free to close this issue when you prefer. Bye!

**Comment by Jason-Rev** [comment]
Hello Tacone,

Thank you for making me aware of your library.  I had not see it before.  It is very cool to see that someone else had the same idea.  
I just took a look at it.  It is nicely documented and clean.  You are right, they are similar. It is also nice to see how someone else approached the same problem.

We have made a conscious effort to keep the number of methods in Sequence low while trying to expand the set of functions that can be used with Sequence.

I can see how useful sleep might be.  We would add sleep as a misc function, fnSleep($seconds) and use it in combination with ->tap, ->tap(fnSleep(5)).

I find it very cool that we had similar ideas.  Do you use Pipe a lot in your code?

Cheers,
Jason

**Comment by tacone** [comment]
I never used it until now. Now I am pushing it into a scraping software, because it encourages me to refrain to use side-effects. I used to write object oriented schedulers, but those pesky classes are terribly difficult to unit-test. While I yet have to write unit-tests for the sw I am working on, I am sure it will be much easier.
The reason I don't use it is, plainly said, that for the most part it does not allow you anything you couldn't do with a plain (and faster) foreach.

Despite that, I am starting to see interesting features I could implement:

- a `->maxTime($seconds)` to end the iteration when the time is over
- allow to emit more than a value from the `map($func)` function. So that it starts to work like a real map reducer:
```php
p($array)->map(function($pipe){
    foreach($pipe as $v) {
          foreach(explode(',', $v) as $token){
                yield $token;
          }
    }
});
````
- in general, better integrating generators, would allow for a easy quick way to keep a limited state while iterating, and thus, for example, yielding a value based on what happened during the previous iterations
- finallly, the biggest feature I miss is creating lazy (incomplete) pipes to achieve reusal:

```php
$encrypt = p()->map('trim')->map('str_rot_13');

foreach ($encrypt($array1) as $v) {
//...
}
foreach ($encrypt($array2) as $v) {
//...
}
foreach ($encrypt($array3)->sleep(0.5) as $v) {
//...
}
```
Pity your stuck to PHP 5.3 compatibility btw :(

Bye!

**Comment by Jason-Rev** [comment]
Hello Tacone,

We use Sequence in our code to reduce side-effects.  Each step in the sequence should have a single purpose.  Our focus is more on maintainability and correctness than on speed.  PHP by nature is not fast.

As far as late binding (lazy pipes), we have taken a couple of approaches:
1. just wrap it in an anonymous function.
2. use FnSequence.  It is part of the Sequence library.

Cheers,
Jason
