### ISSUE TITLE
Sequence::make()->split() ?

### ISSUE THREAD

**Issue by saber3005** [revinate/sequence#7]
This might get into an unsupported area, but would it be possible to add a function to sequence which would split an argument array into an array of smaller arrays based on a filter? I'm thinking of something like this:

```php
list($even, $odd) = Sequence::make(array(1, 2, 3, 4, 5, 6))
    ->split(function($key) {
        return $key % 2 === 0;
    })->to_a();
// => $even == array(2,4,6); $odd == array(1,3,5);
```

**Comment by jrglee** [comment]
A more functional way to look at it would be a 'group by' operation. Check [Scala](http://www.scala-lang.org/api/current/index.html#scala.collection.immutable.List@groupBy[K](f:A=>K):scala.collection.immutable.Map[K,Repr]) and [Lodash](https://lodash.com/docs#groupBy) for examples.

**Comment by Jason-Rev** [comment]
Scala calls it [partition](http://www.scala-lang.org/api/2.7.1/scala/List.html#partition%28%28A%29%3D%3EBoolean%29)

As Jorge said, it really is just a specialized version of groupBy:

```PHP
$evenOdd = Sequence::make(range(1,10))->groupBy(function($n) { return $n % 2 == 0; })->to_a();
```

**Comment by saber3005** [comment]
Ahh, you learn something new every day =)

Thanks!
